// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlightSearchController from "./flight_search_controller"
application.register("flight-search", FlightSearchController)

import FlightSelectController from "./flight_select_controller"
application.register("flight-select", FlightSelectController)

import PassengersController from "./passengers_controller"
application.register("passengers", PassengersController)

import PassengerFormController from "./passenger_form_controller"
application.register("passenger-form", PassengerFormController)

import FormValidationController from "./form_validation_controller"
application.register("form-validation", FormValidationController)

